CREATE TABLE User_Details (
	ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	Username VARCHAR(150) NOT NULL,
	Email VARCHAR(150) NOT NULL,
	Password CHAR(60) NOT NULL,
    Otp CHAR(6),
    Otp_Expiry TIMESTAMP,
	Created_At TIMESTAMP default CURRENT_TIMESTAMP,
    Updated_At TIMESTAMP default CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);